[workspace]
authors = ["rbeutel <rbeutel@eoas.ubc.ca>"]
channels = ["conda-forge", "main", "r", "msys2"]
name = "projection"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
arrow = "*"
bottleneck = "*"
cmocean = "*"
dask = "*"
python-dateutil = "*"
jupyterlab = "*"
matplotlib = "*"
netcdf4 = "*"
numpy = "*"
pandas = "*"
pip = "*"
python = "3.*"
pytz = "*"
scipy = "*"
statsmodels = "*"
xarray = "*"
ipython = "*"
cartopy = "*"
scikit-learn = "*"
geopandas = "*"
gsw = "*"

[pypi-dependencies]
salishseatools = { git = "https://github.com/SalishSeaCast/tools.git", subdirectory = "SalishSeaTools" }
